name = input("Bitte Name eingeben: ")
weight = input("Bitte Körpergewicht in kg: ")
height = input("Bitte Körpergröße in Meter: ")
weight = float(weight)
height = float(height)
body_mass_index = weight/(height**2)
print(f'Berechneter BMI für {name}: {body_mass_index:.2f}')