isbngenerator:
    prefix: "Isbn-"
    suffix: "-dk"
database:
    host: h2908727.stratoserver.net
    port: 3406
    database: javacream
    user: user
    password: user
endpoint:
    url: "http://h2908727.stratoserver.net:8080/api/books"

