# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\npublishing\"b\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\x11\n\tavailable\x18\x02 \x01(\x08\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\r\n\x05price\x18\x05 \x01(\x01\x12\r\n\x05pages\x18\x06 \x01(\x05')



_BOOK = DESCRIPTOR.message_types_by_name['Book']
Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:publishing.Book)
  })
_sym_db.RegisterMessage(Book)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=26
  _BOOK._serialized_end=124
# @@protoc_insertion_point(module_scope)
