START_NUMBER = 1
END_NUMBER = 30
FIRST_DIVISOR = 3
SECOND_DIVISOR = 5
MESSAGE_FOR_FIRST_DIVISOR = "Fizz"
MESSAGE_FOR_SECOND_DIVISOR = "Buzz"
MESSAGE_FOR_FIRST_AND_SECOND_DIVISOR = "FizzBuzz"

counter = START_NUMBER
while (counter <= END_NUMBER):
    DIVIDABLE_BY_FIRST_DIVISOR = (counter % FIRST_DIVISOR == 0)
    DIVIDABLE_BY_SECOND_DIVISOR = (counter % SECOND_DIVISOR == 0)
    DIVIDABLE_BY_FIRST_AND_SECOND_DIVISOR = DIVIDABLE_BY_FIRST_DIVISOR and DIVIDABLE_BY_SECOND_DIVISOR
    

    if DIVIDABLE_BY_FIRST_DIVISOR:
        print(f"{counter}, {MESSAGE_FOR_FIRST_DIVISOR}")
    elif DIVIDABLE_BY_SECOND_DIVISOR:
        print(f"{counter}, {MESSAGE_FOR_SECOND_DIVISOR}")
    elif DIVIDABLE_BY_FIRST_AND_SECOND_DIVISOR:
        print(f"{counter}, {MESSAGE_FOR_FIRST_AND_SECOND_DIVISOR}")
    else:
        print(f"{counter}")
    counter += 1